[server]
port = 6666

[node]
max-sessions = 10
detect-drivers = false

[[node.driver-configuration]]
max-sessions = 5
display-name = "Chrome"
stereotype = { browserName = "chrome"}
options = [
	"--headless",
	"--windows-size= 1024, 1024"
]